[package]
name = "a_pseudo_random_nums"
version = "0.1.0"
authors = ["Himujjal <upadhyayahimujjal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
